# -*- coding: utf-8 -*-
"""Juego.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oCNJdrIvwwkRBJw6QJoZuYTae-8GETbR
"""

import random

# Lista de palabras
palabras = [
    'amarillo', 'azul', 'blanco', 'gris', 'casa', 'cielo', 'claro', 'color', 'comida', 'correr',
    'corto', 'creer', 'cruzar', 'cuadro', 'cuerpo', 'dama', 'dado', 'dulce', 'edad', 'elefante',
    'empezar', 'encontrar', 'entender', 'escalar', 'escribir', 'espacio', 'esperar', 'estrella', 'estudiar', 'feliz',
    'flor', 'frutilla', 'fruta', 'fuego', 'gato', 'girar', 'grande', 'gelatina', 'guitarra', 'hablar',
    'hacer', 'hermano', 'hijo', 'historia', 'hora', 'huevo', 'idea', 'igual', 'jugar', 'largo',
    'leer', 'libro', 'luz', 'madre', 'mano', 'mar', 'mesa', 'mirar', 'mover', 'mujer',
    'naranja', 'negro', 'nueve', 'nube', 'ojo', 'oso', 'padre', 'piso', 'palabra', 'papel',
    'parar', 'paso', 'paz', 'pozo', 'perro', 'pez', 'pie', 'piedra', 'pintar', 'plata',
    'poder', 'pollo', 'prueba', 'punto', 'querer', 'roto', 'risa', 'reloj', 'rojo', 'rosa',
    'saber', 'sal', 'saltar', 'sentir', 'ser', 'silla', 'sol', 'sonreir', 'suave', 'subir',
    'taza', 'termo', 'temprano', 'tiempo', 'tigre', 'tomar', 'toro', 'trabajar', 'tres', 'ver',
    'verde', 'viaje', 'volar', 'volver', 'zapato', 'zorro', 'abrir', 'aceite', 'agua', 'alto',
    'amigo', 'animal', 'dinosaurio', 'arena', 'bajo', 'boca', 'brazo', 'cabeza', 'calor', 'cama',
    'campo', 'carne', 'ciudad', 'clase', 'clave', 'cocina', 'comer', 'copa', 'carro', 'cuerda',
    'dormir', 'duro', 'escuela', 'familia', 'fiesta', 'flaco', 'fuerza', 'gafas', 'gente', 'gracias',
    'hambre', 'hombre', 'invierno', 'foto', 'joven', 'juego', 'lago', 'lento', 'libre', 'llave',
    'lluvia', 'luna', 'madera', 'manzana', 'mariposa', 'mes', 'mono', 'mesa', 'nadar', 'nieve',
    'nuevo', 'oro', 'pan', 'pelo', 'piedra', 'piel', 'pluma', 'puerta', 'queso', 'rata',
    'ropa', 'sopa', 'tigre', 'torta', 'vaca', 'viento', 'vino', 'vivir', 'yerba', 'zumo'
]

# Función para escoger la palabra al azar
def seleccion_palabra():
    palabra_seleccionada = random.choice(palabras)
    return palabra_seleccionada

# Función para verificar letra y crear lista de letras adivinadas
def insertar_letra(palabra_seleccionada, lista_letras_adivinadas):
    letra_elegida = input('Elija una letra: ')

    if letra_elegida.isalpha():
        if letra_elegida not in lista_letras_adivinadas:
            lista_letras_adivinadas.append(letra_elegida)
        else:
            print('Esa letra ya la elegiste')
    else:
        print('El caracter introducido no es una letra del alfabeto.')

# Función para adivinar cada letra
def adivinar_letra(palabra_seleccionada, lista_letras_adivinadas):
    for letra in palabra_seleccionada:
        if letra in lista_letras_adivinadas:
            print(letra, end=' ')
        else:
            print('-', end=' ')
    print()  # Nueva línea después de adivinar la letra

# Función juego
def jugar():
    print('¡Bienvenido al juego de ahorcado!')
    palabra_oculta = seleccion_palabra()
    lista_letras_adivinadas = []
    vidas = 5

    # Mostrar el estado inicial de la palabra oculta
    adivinar_letra(palabra_oculta, lista_letras_adivinadas)

    while vidas > 0:
        # Insertar letra y verificar
        insertar_letra(palabra_oculta, lista_letras_adivinadas)

        # Mostrar el estado actual de la palabra oculta con letras adivinadas
        adivinar_letra(palabra_oculta, lista_letras_adivinadas)

        # Verificar si el jugador ha adivinado todas las letras
        if all(letra in lista_letras_adivinadas for letra in palabra_oculta):
            print("¡Felicidades! Has adivinado la palabra:", palabra_oculta)
            break

        # Disminuir las vidas si la letra no está en la palabra
        if lista_letras_adivinadas[-1] not in palabra_oculta:
            vidas -= 1
            print(f"Letra Incorrecta. Te quedan {vidas} vidas.")

        # Verificar si el jugador ha perdido todas las vidas
        if vidas == 0:
            print("Has perdido. La palabra era:", palabra_oculta)

# Llamar a la función jugar
jugar()